# picogame_cutscene: show a FULLSCREEN image with ~0 RAM, by strip-streaming it from a flash FILE -
# optionally blitted at an integer SCALE (small PAL8 story art -> whole screen), with an optional
# caption bar + wait-for-A. ONE module for every "show a picture" beat: title/intro/ending art,
# narrative story scenes, boss cards.
#
# A 320x240 frame is 150 KB (RGB565) / 75 KB (PAL8) - too big for the ~138 KB heap, and a .mpy const
# would just COPY to the heap (a FAT file is not XIP-mapped). So the image stays on flash as a raw
# ROW-MAJOR file and we read it one ~24-row BAND at a time into a small reused buffer, blitting each
# band straight to the display. Only the band (~w*band bytes) is ever in RAM; the LCD then holds the
# image, so a static cutscene costs nothing after the one render.
#
# Two source shapes, one API:
#   - NATIVE-RES (w = screen width): RGB565 (photo-true, 2 B/px file) or PAL8 + palette (1 B/px).
#   - SMALL + SCALED (story art): a 160x120 PAL8 scene blitted 2x fills 320x240 for a quarter of
#     the flash (19 KB vs 77 KB), chunky-pixel look. scale=None derives it from the display
#     (display.width // w) so the game stays size-independent - don't hardcode the screen size.
#
# Bake PAL8 scenes with `tools/bake_cutscene.py` (PNG -> row-major .dat + a SHARED palette module,
# one palette for all of a game's scenes):
#   import picogame_cutscene as cut
#   from scenes import scene_pal                     # generated by bake_cutscene.py
#   PAL = cut.palette(pg, scene_pal)                 # build the wire palette ONCE at setup
#   cut.show(pg, backend, bufA, "intro.dat")                             # native RGB565
#   cut.show(pg, backend, bufA, "scenes/intro.dat", PAL, w=160, h=120)   # PAL8, auto 2x on 320
#   cut.play(pg, backend, bufA, btn, "scenes/intro.dat", PAL, w=160, h=120,
#            caption="The wyrm came at dusk.", clock=clock)              # + caption + wait A/B
#   scene.invalidate()                               # the image clobbered the LCD - repaint after
#
# IMMEDIATE-MODE LANDMINE (this bit on real hardware): pg.render() needs the raw BusDisplay
# (board.DISPLAY), NOT the game's fast/DMA backend (the `display` you pass from setup()) - on
# device that backend isn't a BusDisplay and pg.render raises "expected a BusDisplay". The sim
# aliases the two, so it only shows on hardware. This module therefore renders to board.DISPLAY
# itself; the `display` argument is kept for API symmetry and used only as a fallback where
# board.DISPLAY doesn't exist (e.g. framebuffer platforms).

from array import array
import time

try:
    import board
    _LCD = getattr(board, "DISPLAY", None)
except ImportError:                                    # no board module (bare test host)
    _LCD = None

CAP_FG = (235, 238, 248)                               # caption text / bar colours (RGB triplets)
CAP_BG = (6, 6, 10)


def palette(pg, rgb):
    """Build the device palette (array('H') of wire RGB565, via pg.rgb565 - never hand-pack 565)
    from a bake_cutscene.py palette module (its RGB tuple), a list of (r, g, b) triplets, or a list
    of already-wire ints (returned as array('H') unchanged, no copy if already one).
    Build it ONCE at setup and pass the result around - show() would otherwise rebuild it per call."""
    rgb = getattr(rgb, "RGB", rgb)                     # a palette module -> its RGB tuple
    if isinstance(rgb, array):
        return rgb
    if len(rgb) and not isinstance(rgb[0], int):       # (r, g, b) triplets -> wire
        return array("H", [pg.rgb565(r, g, b) for (r, g, b) in rgb])
    return array("H", rgb)                             # wire ints in a plain list


def show(pg, display, buffer, path, pal=None, w=320, h=240, scale=None, band=24, bg=0):
    """Stream the w x h image at `path` from flash band-by-band through `buffer` (your strip
    buffer) and blit each band at an integer `scale` - a full-screen frame with 0 retained RAM.
    `pal` (as from palette()) selects PAL8 (1 B/px file); None = RGB565 (2 B/px, photo-true).
    scale=None derives it from the display: width // w, and REJECTS a non-integer fit (a 150-wide
    image on a 320 screen has no whole-pixel scale - re-bake at a divisor size). Returns the
    scale used. `bg` = the palette index (PAL8) / byte (RGB565) clearing a short final band."""
    dst = _LCD if _LCD is not None else display        # immediate render -> the raw BusDisplay
    if scale is None:
        scale = dst.width // w
        if scale < 1 or dst.width % w:
            raise ValueError("no integer scale: image w=%d vs display w=%d" % (w, dst.width))
        if h * scale != dst.height:                    # fullscreen contract: must fill BOTH axes
            raise ValueError("image %dx%d at %dx doesn't fill the %dx%d screen (%d rows left); "
                             "re-bake at a size that divides the display, or pass an explicit scale"
                             % (w, h, scale, dst.width, dst.height, dst.height - h * scale))
    elif scale < 1 or int(scale) != scale:
        raise ValueError("scale must be a positive integer, got %r" % (scale,))
    if pal is not None:
        pal = palette(pg, pal)                         # no-op if already an array('H')
        fmt, bpp = pg.PAL8, 1
    else:
        fmt, bpp = pg.RGB565, 2
    rowbuf = bytearray(w * band * bpp)                 # ONE source band
    bmp = pg.Bitmap(rowbuf, w, band, format=fmt, palette=pal, frames=1, stride=w)
    spr = pg.Sprite(bmp, 0, 0)
    if scale != 1:
        spr.scale = scale
    row_bytes = w * bpp
    with open(path, "rb") as f:
        sy = 0
        while sy < h:
            rows = band if sy + band <= h else h - sy   # this band (the last may be shorter)
            want = rows * row_bytes                      # EXACT bytes for those rows
            r = f.readinto(memoryview(rowbuf)[:want])
            if r != want:                                # truncated file -> fail, don't leave it stale
                raise OSError("cutscene: %s truncated at row %d (%d/%d bytes)"
                              % (path, sy, r or 0, want))
            if want < len(rowbuf):                        # a short final band: clear the unused tail
                for i in range(want, len(rowbuf)):
                    rowbuf[i] = bg
            dy = sy * scale
            spr.move(0, dy)
            spr.touch()                                   # pixels changed in place -> force the blit
            pg.render(dst, [spr], buffer, 0, dy, w * scale, dy + rows * scale, background=0)
            sy += rows
    return scale


def play(pg, display, buffer, btn, path, pal=None, w=320, h=240, scale=None, band=24,
         caption=None, caption_lines=None, auto_hold=0, clock=None, bg=0):
    """A full-screen picture beat: show() the image, overlay optional caption line(s) in a dark
    bar at the bottom, then block until A/B is pressed (polling `btn`) - or, with auto_hold > 0,
    auto-advance after that many ticks (AUTOPLAY sim runs / a btn-less timed beat; btn may then be
    None). `caption` is the one-line convenience for caption_lines=[caption]; `clock`
    (picogame_clock) paces the wait loop (a plain sleep without it). IMMEDIATE mode - the image
    lives on the LCD, nothing refreshes: the caller fades its live scene OUT first and MUST
    scene.invalidate() after (the image clobbered the LCD)."""
    if btn is None and not auto_hold:
        raise ValueError("play needs btn (wait for A/B) or auto_hold > 0")
    dst = _LCD if _LCD is not None else display
    show(pg, display, buffer, path, pal, w, h, scale, band, bg)
    lines = caption_lines if caption_lines else ([caption] if caption else None)
    if lines:
        import terminalio                              # only pulled in when a caption is drawn
        import picogame_font
        fg = pg.rgb565(*CAP_FG)
        cbg = pg.rgb565(*CAP_BG)
        y0 = dst.height - (12 * len(lines) + 8)
        pg.render(dst, [], buffer, 0, y0, dst.width, dst.height, background=cbg)  # dark caption bar
        for i, line in enumerate(lines):
            lbl = picogame_font.Label(pg, terminalio.FONT, 8, y0 + 5 + i * 12, fg, cbg)
            lbl.set(line)
            lbl.draw(dst, buffer)
    if btn is not None:
        btn.poll()                                     # flush: a press still held from BEFORE the
    t = 0                                              # scene must not dismiss it instantly
    while True:
        if btn is not None:
            btn.poll()
            if btn.just_pressed(btn.A) or btn.just_pressed(btn.B):
                return
        t += 1
        if auto_hold and t > auto_hold:
            return
        if clock is not None:
            clock.tick()
        else:
            time.sleep(0.03)
